async function loadEchoes(){
  const host=document.getElementById('dynamicContent');
  try{
    const fresh=path=>fetch(path,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.text()});
    const [a,b1,b2]=await Promise.all([fresh('content-a.html'),fresh('content-b1.html'),fresh('content-b2.html')]);
    host.innerHTML=a+b1+b2;
    initEchoes();
  }catch(e){host.innerHTML='<p class="loading">Unable to load the experience. Please refresh.</p>';console.error(e);}
}
function initEchoes(){
const langButton=document.getElementById('langButton');
let lang=localStorage.getItem('echoes-lang')||'en';
let selectedRune='root';
function applyLang(){document.documentElement.lang=lang;document.querySelectorAll('[data-en][data-es]').forEach(el=>el.textContent=el.dataset[lang]);langButton.textContent=lang==='en'?'ES':'EN';const preview=document.getElementById('previewLink');if(preview)preview.href=lang==='en'?'preview-en.html':'preview.html';renderRune(selectedRune)}
langButton.onclick=()=>{lang=lang==='en'?'es':'en';localStorage.setItem('echoes-lang',lang);applyLang()};
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
function renderRune(key){const d=runeData[key]||runeData.root;selectedRune=key in runeData?key:'root';document.querySelectorAll('.rune-node').forEach(b=>{b.classList.toggle('active',b.dataset.rune===selectedRune);b.setAttribute('aria-pressed',b.dataset.rune===selectedRune)});const l=lang==='es'?'es':'en';const img=document.getElementById('runePanelImage');img.src=d.image;img.alt=d.title[l];document.getElementById('runePanelType').textContent=d.type[l];document.getElementById('runePanelTitle').textContent=d.title[l];document.getElementById('runePanelWorld').textContent=d.world[l];document.getElementById('runePanelDescription').textContent=d.description[l];document.getElementById('runePanelIdentity').textContent=d.identity[l];const ul=document.getElementById('runePanelAbilities');ul.replaceChildren(...d.abilities[l].map(x=>{const li=document.createElement('li');li.textContent=x;return li}));const fav=document.getElementById('favoriteRune').value;document.getElementById('choiceFeedback').textContent=fav===d.title.en?(l==='es'?'✓ Esta es tu elección actual.':'✓ This is your current choice.') : ''}
document.querySelectorAll('.rune-node').forEach(b=>b.onclick=()=>renderRune(b.dataset.rune));document.getElementById('chooseRune').onclick=()=>{const d=runeData[selectedRune];document.getElementById('favoriteRune').value=d.title.en;document.getElementById('choiceFeedback').textContent=lang==='es'?'✓ Guardada como la runa que desbloquearías primero.':'✓ Saved as the rune you would unlock first.'};
const form=document.getElementById('echoesSurvey'),result=document.getElementById('surveyResult'),output=document.getElementById('surveyOutput');
function setConditional(panel,show,requiredNames=[]){panel.classList.toggle('visible',show);panel.querySelectorAll('input,select,textarea').forEach(el=>{el.disabled=!show;el.required=show&&requiredNames.includes(el.name)})}
function updateSurvey(){const interests=[...form.querySelectorAll('input[name="interest"]:checked')].map(x=>x.value),mixed=form.querySelector('input[name="mixedFormat"]:checked')?.value||'';const wantsNovel=interests.includes('Novel')||interests.includes('Mixed experience')&&mixed.includes('Novel'),wantsGame=interests.includes('Game')||interests.includes('Mixed experience')&&mixed.includes('Game');setConditional(document.getElementById('mixedQuestions'),interests.includes('Mixed experience'),['mixedFormat']);setConditional(document.getElementById('novelQuestions'),wantsNovel,['novelFormat']);setConditional(document.getElementById('gameQuestions'),wantsGame,['gamePrice']);const physical=form.querySelector('input[name="novelFormat"]:checked')?.value||'';setConditional(document.getElementById('physicalQuestions'),wantsNovel&&(physical==='Physical'||physical==='Both'),['physicalEdition','premiumExtras'])}
form.addEventListener('change',updateSurvey);updateSurvey();
form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),ints=fd.getAll('interest'),platforms=fd.getAll('platform'),gameVisible=document.getElementById('gameQuestions').classList.contains('visible'),submit=document.getElementById('surveySubmit'),error=document.getElementById('surveyError');if(gameVisible&&!platforms.length){const first=form.querySelector('input[name="platform"]');first.setCustomValidity(lang==='es'?'Elige al menos una plataforma.':'Choose at least one platform.');first.reportValidity();first.onchange=()=>first.setCustomValidity('');return}const summary=['ECHOES OF FRACTURED WORLDS — EARLY AUDIENCE FEEDBACK','Interests: '+(ints.length?ints.join(', '):'Not specified'),'Novel format: '+(fd.get('novelFormat')||'Not applicable'),'Physical edition: '+(fd.get('physicalEdition')||'Not applicable'),'Premium extras: '+(fd.get('premiumExtras')||'Not applicable'),'Platforms: '+(platforms.length?platforms.join(', '):'Not applicable'),'Mixed experience: '+(fd.get('mixedFormat')||'Not applicable'),'Preferred language: '+(fd.get('language')||''),'Comfortable game price: '+(fd.get('gamePrice')||'Not applicable'),'Strongest hook: '+(fd.get('hook')||''),'Rune I would unlock first: '+(fd.get('favoriteRune')||'Not selected'),'Wants updates: '+(fd.get('updates')?'Yes':'No'),'Comment: '+(fd.get('comment')||'—')].join('\n');error.hidden=true;submit.disabled=true;submit.textContent=lang==='es'?'Enviando…':'Sending…';try{const response=await fetch(form.action,{method:'POST',body:fd,headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Submission failed');output.textContent=summary;result.hidden=false;form.reset();updateSurvey();result.scrollIntoView({behavior:'smooth',block:'center'})}catch(err){error.textContent=lang==='es'?'No pudimos enviar tus respuestas. Revisa tu conexión e inténtalo de nuevo.':'We could not send your answers. Check your connection and try again.';error.hidden=false}finally{submit.disabled=false;submit.textContent=lang==='es'?'Enviar mis respuestas':'Send my feedback'}};
applyLang();renderRune('root');
}
loadEchoes();

